FLASH_CLASS NOR
CHIP_NAME BY25Q64AS
STORAGE_FILE by25q64as_mod_storage.bin

MEMORY_SIZE 8388608
PAGE_SIZE 256
SECTOR_SIZE 4096
BLOCK32_SIZE 32768
BLOCK64_SIZE 65536
ADDRESS_BYTES 3

JEDEC_ID 68 40 17
HAS_SECURITY_REGISTERS 1
SECURITY_REGISTER_COUNT 3
SECURITY_REGISTER_SIZE 256
RESET_STORAGE_ON_START 1
AUTO_COMPLETE 0
WRAP_ADDRESS 1

F_C_MHZ 108
F_R_MHZ 55
F_Q_MHZ 108
T_PP_US 600
T_PP_MAX_US 2400
T_SE_US 50000
T_BE32_US 150000
T_BE64_US 250000
T_CE_US 25000000
T_RESET_US 30
