FLASH_CLASS NOR
CHIP_NAME GD25L_SIMPLIFIED
STORAGE_FILE gd25l_mod_storage.bin

MEMORY_SIZE 33554432
PAGE_SIZE 256
SECTOR_SIZE 4096
BLOCK32_SIZE 32768
BLOCK64_SIZE 65536
ADDRESS_BYTES 3

JEDEC_ID C8 60 16
RESET_STORAGE_ON_START 1
AUTO_COMPLETE 0
WRAP_ADDRESS 1

F_C_MHZ 104
F_R_MHZ 50
T_PP_US 250
T_SE_US 30000
T_BE64_US 150000
T_CE_US 10000000
