FLASH_CLASS NOR
CHIP_NAME M25P40
STORAGE_FILE m25p40_mod_storage.bin

MEMORY_SIZE 524288
PAGE_SIZE 256
SECTOR_SIZE 65536
BLOCK32_SIZE 65536
BLOCK64_SIZE 65536
ADDRESS_BYTES 3

JEDEC_ID 20 20 13
RESET_STORAGE_ON_START 1
AUTO_COMPLETE 0
WRAP_ADDRESS 1

F_C_MHZ 75
F_R_MHZ 33
T_PUW_US 10000
T_PP_US 800
T_PP_MAX_US 5000
T_SE_US 600000
T_CE_US 4500000
T_RESET_US 30
