FLASH_CLASS SPI_NAND
CHIP_NAME GD5F1GM7UEYIGR
STORAGE_FILE gd5f1gm7_mod_storage.bin

MAIN_SIZE 2048
SPARE_SIZE 128
PAGE_SIZE 2176
PAGES_PER_BLOCK 64
BLOCKS 1024
PLANES 1

JEDEC_ID C8 91
DEFAULT_ALL_PROTECTED 1
FEATURE_A0_DEFAULT 0x38
FEATURE_B0_DEFAULT 0x10
ECC_SUPPORTED 1
ECC_ENABLE 1
ECC_RESERVED_START 0x840
ECC_RESERVED_END 0x880
GENERATE_INTERNAL_ECC_PARITY 1
BAD_BLOCK_MARKER_COLUMN 2048
MAX_PARTIAL_PROGRAMS 4
STRICT_SEQUENTIAL_PROGRAM 1
STRICT_BAD_BLOCK 1
PROGRAM_LOAD_REQUIRES_WEL 0
RESET_STORAGE_ON_START 1
AUTO_COMPLETE 0

F_CLOCK_MHZ 133
F_READ_MHZ 133
F_QUAD_MHZ 133
T_READ_ECC_OFF_US 25
T_READ_ECC_ON_US 50
T_PROG_US 320
T_PROG_MAX_US 600
T_ERASE_US 3000
T_ERASE_MAX_US 10000
T_RESET_US 500
