FLASH_CLASS SPI_NAND
CHIP_NAME W25N01GVZEIG
STORAGE_FILE w25n01gv_mod_storage.bin

MAIN_SIZE 2048
SPARE_SIZE 64
PAGE_SIZE 2112
PAGES_PER_BLOCK 64
BLOCKS 1024
PLANES 1

JEDEC_ID EF AA 21
DEFAULT_ALL_PROTECTED 1
FEATURE_A0_DEFAULT 0x7C
FEATURE_B0_DEFAULT 0x18
ECC_SUPPORTED 1
ECC_ENABLE 1
ECC_RESERVED_START 2048
ECC_RESERVED_END 2112
MAX_PARTIAL_PROGRAMS 4
MAX_BBM_ENTRIES 20
STRICT_SEQUENTIAL_PROGRAM 1
PROGRAM_LOAD_REQUIRES_WEL 1
RESET_STORAGE_ON_START 1
AUTO_COMPLETE 0

F_CLOCK_MHZ 104
F_READ_MHZ 104
F_QUAD_MHZ 104
T_PUW_US 5000
T_READ_ECC_OFF_US 25
T_READ_ECC_ON_US 60
T_PROG_US 250
T_PROG_MAX_US 700
T_ERASE_US 2000
T_ERASE_MAX_US 10000
T_RESET_US 500
